from colorama import Fore, Style

RED = Fore.LIGHTRED_EX
WHITE = Fore.LIGHTWHITE_EX
GREEN = Fore.LIGHTGREEN_EX
YELLOW = Fore.LIGHTYELLOW_EX
BLUE = Fore.LIGHTBLUE_EX
RESET = Style.RESET_ALL
BLACK = Fore.LIGHTBLACK_EX